import prisma from '../prisma/client';

const clienteSafeSelect = {
  id: true,
  codigo: true,
  nombre: true,
  email: true,
  telefono: true,
  creadoEn: true,
  role: true,
  avatar: true,
  ciudad: true,
  idioma: true,
} as const;

export const ChatModel = {
  async findAll(filter: any = {}) {
    return prisma.chat.findMany({
      where: filter,
      include: { mensajes: true, cliente: { select: clienteSafeSelect }, pedido: true },
      orderBy: { creadoEn: 'desc' }
    });
  },
  async findById(id: number) {
    return prisma.chat.findUnique({
      where: { id },
      include: { mensajes: true, cliente: { select: clienteSafeSelect }, pedido: true }
    });
  },
  async create(data: any) {
    const { mensajes, ...chatData } = data;
    const mensajesCreate = Array.isArray(mensajes)
      ? mensajes.map((m: any) => ({
          // Back-compat: accept both naming styles
          autor: m?.autor ?? m?.remitente,
          texto: m?.texto ?? m?.contenido,
          // `fecha` is generated by DB default
        }))
      : undefined;

    return prisma.chat.create({
      data: {
        ...chatData,
        mensajes: mensajesCreate ? { create: mensajesCreate } : undefined
      },
      include: { mensajes: true }
    });
  },
  async update(id: number, data: any) {
    return prisma.chat.update({
      where: { id },
      data,
      include: { mensajes: true }
    });
  },
  async delete(id: number) {
    return prisma.$transaction([
      prisma.mensaje.deleteMany({ where: { chatId: id } }),
      prisma.chat.delete({ where: { id } }),
    ]);
  },
  async addMensaje(chatId: number, mensaje: any) {
    const payload = {
      autor: mensaje?.autor ?? mensaje?.remitente,
      texto: mensaje?.texto ?? mensaje?.contenido,
      chatId,
    };
    return prisma.mensaje.create({
      data: payload
    });
  },
  async deleteMensaje(id: number) {
    return prisma.mensaje.delete({ where: { id } });
  }
};
